import os
from datetime import datetime

def generate_html_report(response_text):
    """Generate an HTML report with the API response."""
    now = datetime.now()
    date_str = now.strftime("%Y%m%d_%H%M")
    report_filename = f"report_risonCc_{date_str}.html"
    
    # Basic HTML formatting
    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rison Copy Checker Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            color: #333;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background: #fff;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #052123;
            text-align: center;
            padding-bottom: 10px;
            border-bottom: 2px solid #97F4FC;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        th, td {{
            padding: 12px 15px;
            border: 1px solid #ddd;
            text-align: left;
        }}
        th {{
            background-color: #052123;
            color: #fff;
        }}
        tr:nth-child(even) {{
            background-color: #f2f2f2;
        }}
        .footer {{
            text-align: center;
            margin-top: 30px;
            font-size: 0.8em;
            color: #777;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Rison Copy Checker Report</h1>
        <p><strong>Generated on:</strong> {now.strftime("%Y-%m-%d %H:%M:%S")}</p>
        
        <div class="report-content">
            {response_text}
        </div>
        
        <div class="footer">
            <p>Generated by Rison Copy Checker | © {now.year}</p>
        </div>
    </div>
</body>
</html>
"""
    
    # Write the HTML content to a file
    with open(report_filename, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    return os.path.abspath(report_filename)


def generate_markdown_report(response_text):
    """Generate a Markdown report with the API response."""
    now = datetime.now()
    date_str = now.strftime("%Y%m%d_%H%M")
    report_filename = f"report_risonCc_{date_str}.md"
    
    # Format the Markdown content
    markdown_content = f"""# Rison Copy Checker Report

**Generated on:** {now.strftime("%Y-%m-%d %H:%M:%S")}

## Analysis Results

{response_text}

---

*Generated by Rison Copy Checker | © {now.year}*
"""
    
    # Write the Markdown content to a file
    with open(report_filename, "w", encoding="utf-8") as f:
        f.write(markdown_content)
        
    return os.path.abspath(report_filename)